### ISSUE TITLE
Complete docker-compose configuration

### ISSUE THREAD

**Issue by pudo** [pudo/spendb#10]
The included ``Dockerfile`` will only set up the ``spendb`` Python application. To fully run the service, a Postgres database is needed as well as some sort of processing queue. These different services should be orchestrated via the ``docker-compose.yml`` configuration, which would also start the background service for data imports. 

(@milafrerichs do you know your way around this stuff?)

**Comment by milafrerichs** [comment]
yes I will take a crack on this today or this weekend.

**Comment by pudo** [comment]
Very cool! Give me a shout if you have any questions!

**Comment by pudo** [comment]
Now got the first version running: http://spendb.pudo.org/ -- thanks Mila, your ``docker-compose.yml`` was perfect I just needed to bind gunicorn to 0.0.0.0 (not 127.0.0.1).
