### ISSUE TITLE
Query view broken in Safari

### ISSUE THREAD

**Issue by milafrerichs** [pudo/spendb#22]
Got an error visiting this site:
https://spendb-dev.herokuapp.com/datasets/wb_contract_awards?view=facts

> [Error] Error: undefined is not a function (evaluating 'api.endsWith("/")')

Works in Chrome but not in Safari

**Comment by pudo** [comment]
Fixed via: https://github.com/pudo/angular-cubes/commit/29cd6ba9bbadc2bbde9ea71b8606ec530b05a1b9 -- thanks for the report.
