### ISSUE TITLE
Angular testing

### ISSUE THREAD

**Issue by nathanhilbert** [pudo/spendb#6]
I've only just started by first angular application the other week, so I'm no expert.  But, I found [ngbp](https://github.com/ngbp/ngbp) to be a big help.  Still trying to figure out angular testing in general.
Maybe I'll port over your work to the way I would approach it if I get time today.  Then you can take it or leave it.

**Comment by nathanhilbert** [comment]
See example [here](https://github.com/nathanhilbert/datamanager_OS) with instructions.  It only has two tests in the .spec files at this time.
This would take out any front-end logic using webassets in flask, making for more isolated development and the ability to separate static files outside of the application server (this is probably possible using webassets, I'm just not aware of it).  
To do items include to make real next step after someone enters validate data in the form to manage dimensions.  
I did break your chosen selection.  There should be more time later in the week to work on this.  Or we can discuss direction.

**Comment by pudo** [comment]
That looks very interesting, I was completely unaware of the state mechanism in Angular. As for completely separating the packages, I'm a bit reluctant to do it as it makes it more complex to get the thing running, while creating a somewhat phony separation: you couldn't run the JS bits without the main app anyway. I've done this in the past with another project (grano/grano-ui) and it just ended up as a permanent support issue ("You didn't install the UI, rtfm").

On the other hand, it would be important to have the independently re-usable bits in separate packages. Your ongoing work on [cubes_dataviewer](https://github.com/USStateDept/cubes_dataviewer) seems like a good example, I'd love to find a way of plugging that into OS. 

It would be great to catch up some time this week, if you're free. IRC or Skype would be ideal.

**Comment by nathanhilbert** [comment]
I wonder if submodules in Angular wouldn't be appropriate here.  I'm trying
to think of ways to have the user download one big cached js file, which
"grunt compile" does, but not necessarily have the extra script running
anything like factories and services that aren't applicable to the current
section of the site. Another idea would be to have the separate parts, but
use git submodules more over the current OS linking.  Then, you aren't
installing as much as running one command that will have the compiled
code.  If someone wants to dev on the submodule, then they have to run
grunt to recompile.  This is the practice of [GeoNode](
https://github.com/GeoNode/geonode) currently and that seems to run into
the community not knowing where to edit the js.  I guess I'm saying there's
no good options at the moment.

Yes, let's discuss on IRC either tomorrow or Wednesday.  Are Cape Town and
Berlin similar time zones?  Or a better question would be where are you
located? Anyway, any time between 8AM - 4PM New York time.  If that doesn't
work, then we can do something my evening.

**Comment by pudo** [comment]
Closing this as we now have a harness (thanks to #21). Still need to roll out tests, though.
